# Testing Pipeline

trigger:
- master
- mac-compliance

strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"
    mac:
      imageName: "macos-10.13"
  maxParallel: 2

pool:
  vmImage: $(imageName)

steps:

- checkout: self

- bash: |

    for TEST_FILE in test/sh/*
    do
      echo ""
      echo ""
      echo "###################"
      echo "# test $TEST_FILE"
      echo "###################"
      echo ""
      chmod +x "$TEST_FILE"
      "./$TEST_FILE"
      if [ $? != 0 ]; then
        exit 1
      fi
    done

  displayName: 'Run testing'
